"""Create notebook 07: Consensus Model + Stacking + Target-Specific + Threshold Analysis."""
import json
from pathlib import Path

NB_PATH = Path(r'e:\PhD_Projecttttttttttttt\PhD_QSAR_Leishmania\notebooks\07_consensus_model.ipynb')

cells = []

def md(source):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": source})

def code(source):
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {},
                  "outputs": [], "source": source})

# ── Header ──
md([
    "# Notebook 07 — Consensus Model, Stacking & Advanced Analysis\n",
    "\n",
    "**Project**: ML-Based QSAR Modeling for Anti-Leishmanial Sulfonamide Derivatives  \n",
    "**Input**: Trained models (RF, SVM, XGB, LGBM), selected features, curated data  \n",
    "**Output**:\n",
    "- Consensus voting model (majority ≥3/4)\n",
    "- Stacking ensemble (meta-learner on base predictions)\n",
    "- Target-specific model analysis\n",
    "- Activity threshold sensitivity (pIC50 = 5.0 vs 6.0)\n",
    "\n",
    "---"
])

# ── Cell 1: Imports ──
code([
    "# ============================================================\n",
    "# CELL 1: Imports and Configuration\n",
    "# ============================================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from pathlib import Path\n",
    "import warnings, sys, joblib\n",
    "from datetime import datetime\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.model_selection import StratifiedKFold, cross_val_predict\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import (\n",
    "    balanced_accuracy_score, f1_score, matthews_corrcoef,\n",
    "    roc_auc_score, classification_report, confusion_matrix\n",
    ")\n",
    "from imblearn.over_sampling import SMOTE\n",
    "from imblearn.pipeline import Pipeline as ImbPipeline\n",
    "\n",
    "SEED = 42\n",
    "np.random.seed(SEED)\n",
    "\n",
    "PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n",
    "sys.path.insert(0, str(PROJECT_ROOT))\n",
    "DATA = PROJECT_ROOT / 'data' / 'processed'\n",
    "MODELS = PROJECT_ROOT / 'models'\n",
    "RESULTS = PROJECT_ROOT / 'results' / 'model_metrics'\n",
    "FIGURES = PROJECT_ROOT / 'figures'\n",
    "\n",
    "for d in [RESULTS, FIGURES]:\n",
    "    d.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "print(f'Project root: {PROJECT_ROOT}')\n",
    "print(f'Timestamp: {datetime.now().strftime(\"%Y-%m-%d %H:%M\")}')\n",
])

# ── Cell 2: Load Data & Models ──
code([
    "# ============================================================\n",
    "# CELL 2: Load Data and Models\n",
    "# ============================================================\n",
    "\n",
    "X_train = pd.read_csv(DATA / 'X_train_selected.csv', index_col=0)\n",
    "X_test  = pd.read_csv(DATA / 'X_test_selected.csv',  index_col=0)\n",
    "y_train_df = pd.read_csv(DATA / 'y_train.csv', index_col=0)\n",
    "y_test_df  = pd.read_csv(DATA / 'y_test.csv',  index_col=0)\n",
    "\n",
    "common_tr = X_train.index.intersection(y_train_df.index)\n",
    "common_te = X_test.index.intersection(y_test_df.index)\n",
    "X_train = X_train.loc[common_tr]\n",
    "X_test  = X_test.loc[common_te]\n",
    "y_train = (y_train_df.loc[common_tr, 'activity_class'] == 'Active').astype(int)\n",
    "y_test  = (y_test_df.loc[common_te,  'activity_class'] == 'Active').astype(int)\n",
    "\n",
    "print(f'X_train: {X_train.shape}  |  X_test: {X_test.shape}')\n",
    "print(f'y_train: {y_train.shape} (Active={y_train.sum()})  |  y_test: {y_test.shape} (Active={y_test.sum()})')\n",
    "\n",
    "rf   = joblib.load(MODELS / 'rf_classifier.joblib')\n",
    "svm  = joblib.load(MODELS / 'svm_classifier.joblib')\n",
    "xgb  = joblib.load(MODELS / 'xgb_classifier.joblib')\n",
    "lgbm = joblib.load(MODELS / 'lgbm_classifier.joblib')\n",
    "\n",
    "models = {'RF': rf, 'SVM': svm, 'XGBoost': xgb, 'LightGBM': lgbm}\n",
    "print(f'\\nLoaded {len(models)} models: {list(models.keys())}')\n",
])

# ── Section: Consensus Model ──
md([
    "## Part A — Consensus Voting Model\n",
    "\n",
    "A compound is predicted **Active** only if ≥3 out of 4 models agree."
])

code([
    "# ============================================================\n",
    "# CELL 3: Consensus Voting (≥3/4 majority)\n",
    "# ============================================================\n",
    "\n",
    "def consensus_predict(X, models, threshold=3):\n",
    "    preds = np.array([m.predict(X) for m in models.values()])\n",
    "    votes = preds.sum(axis=0)\n",
    "    consensus = (votes >= threshold).astype(int)\n",
    "    confidence = votes / len(models)\n",
    "    return consensus, confidence\n",
    "\n",
    "def consensus_predict_proba(X, models):\n",
    "    probas = np.array([m.predict_proba(X)[:, 1] for m in models.values()])\n",
    "    return probas.mean(axis=0)\n",
    "\n",
    "# Evaluate each model + consensus on TEST set\n",
    "results = []\n",
    "for name, model in models.items():\n",
    "    y_pred = model.predict(X_test)\n",
    "    y_prob = model.predict_proba(X_test)[:, 1]\n",
    "    results.append({\n",
    "        'Model': name,\n",
    "        'Balanced_Accuracy': balanced_accuracy_score(y_test, y_pred),\n",
    "        'F1': f1_score(y_test, y_pred),\n",
    "        'MCC': matthews_corrcoef(y_test, y_pred),\n",
    "        'ROC_AUC': roc_auc_score(y_test, y_prob),\n",
    "    })\n",
    "\n",
    "# Consensus\n",
    "cons_pred, cons_conf = consensus_predict(X_test, models)\n",
    "cons_prob = consensus_predict_proba(X_test, models)\n",
    "results.append({\n",
    "    'Model': 'Consensus (≥3/4)',\n",
    "    'Balanced_Accuracy': balanced_accuracy_score(y_test, cons_pred),\n",
    "    'F1': f1_score(y_test, cons_pred),\n",
    "    'MCC': matthews_corrcoef(y_test, cons_pred),\n",
    "    'ROC_AUC': roc_auc_score(y_test, cons_prob),\n",
    "})\n",
    "\n",
    "results_df = pd.DataFrame(results)\n",
    "print('=== Test Set Performance ===')\n",
    "print(results_df.round(4).to_string(index=False))\n",
])

# ── Section: Stacking Ensemble ──
md([
    "## Part B — Stacking Ensemble\n",
    "\n",
    "Train a **meta-learner** (Logistic Regression) on out-of-fold predictions from base models."
])

code([
    "# ============================================================\n",
    "# CELL 4: Stacking Ensemble (meta-learner)\n",
    "# ============================================================\n",
    "\n",
    "print('Generating out-of-fold predictions for stacking...')\n",
    "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
    "\n",
    "oof_preds = {}\n",
    "test_preds = {}\n",
    "\n",
    "for name, model in models.items():\n",
    "    print(f'  {name}: cross-validating...')\n",
    "    oof_prob = cross_val_predict(model, X_train, y_train, cv=cv,\n",
    "                                 method='predict_proba', n_jobs=-1)[:, 1]\n",
    "    oof_preds[name] = oof_prob\n",
    "    test_preds[name] = model.predict_proba(X_test)[:, 1]\n",
    "\n",
    "# Build meta-features\n",
    "meta_train = pd.DataFrame(oof_preds)\n",
    "meta_test  = pd.DataFrame(test_preds)\n",
    "\n",
    "print(f'\\nMeta-train shape: {meta_train.shape}')\n",
    "print(f'Meta-test shape:  {meta_test.shape}')\n",
    "\n",
    "# Train meta-learner\n",
    "meta_model = LogisticRegression(random_state=SEED, max_iter=1000)\n",
    "meta_model.fit(meta_train, y_train)\n",
    "\n",
    "# Evaluate stacking on test set\n",
    "stack_pred = meta_model.predict(meta_test)\n",
    "stack_prob = meta_model.predict_proba(meta_test)[:, 1]\n",
    "\n",
    "stack_metrics = {\n",
    "    'Model': 'Stacking (LR meta)',\n",
    "    'Balanced_Accuracy': balanced_accuracy_score(y_test, stack_pred),\n",
    "    'F1': f1_score(y_test, stack_pred),\n",
    "    'MCC': matthews_corrcoef(y_test, stack_pred),\n",
    "    'ROC_AUC': roc_auc_score(y_test, stack_prob),\n",
    "}\n",
    "\n",
    "results_df = pd.concat([results_df, pd.DataFrame([stack_metrics])], ignore_index=True)\n",
    "print('\\n=== Updated Test Set Performance (with Stacking) ===')\n",
    "print(results_df.round(4).to_string(index=False))\n",
    "\n",
    "# Save meta-model\n",
    "joblib.dump(meta_model, MODELS / 'stacking_meta_model.joblib')\n",
    "print('\\nStacking meta-model saved.')\n",
    "\n",
    "# Meta-learner coefficients (which base model matters most)\n",
    "print('\\nMeta-learner coefficients:')\n",
    "for name, coef in zip(models.keys(), meta_model.coef_[0]):\n",
    "    print(f'  {name}: {coef:.4f}')\n",
])

# ── Section: Target-Specific Models ──
md([
    "## Part C — Target-Specific Models\n",
    "\n",
    "Train separate RF models for each organism to see if target-specific models perform better."
])

code([
    "# ============================================================\n",
    "# CELL 5: Target-Specific Models\n",
    "# ============================================================\n",
    "\n",
    "curated = pd.read_csv(DATA / 'curated_dataset.csv')\n",
    "train_set = pd.read_csv(DATA / 'train_set.csv')\n",
    "test_set  = pd.read_csv(DATA / 'test_set.csv')\n",
    "\n",
    "scaler = joblib.load(MODELS / 'scaler.joblib')\n",
    "features = pd.read_csv(DATA / 'selected_features.csv')['feature'].tolist()\n",
    "\n",
    "# Full descriptor matrices (unscaled)\n",
    "X_tr_full = pd.read_csv(DATA / 'X_train.csv', index_col=0)\n",
    "X_te_full = pd.read_csv(DATA / 'X_test.csv', index_col=0)\n",
    "\n",
    "targets = curated['target_name'].unique()\n",
    "print(f'Targets: {targets.tolist()}')\n",
    "print(f'Compounds per target:')\n",
    "for t in targets:\n",
    "    n = (curated['target_name'] == t).sum()\n",
    "    print(f'  {t}: {n:,}')\n",
    "\n",
    "target_results = []\n",
    "\n",
    "for target in targets:\n",
    "    # Get SMILES for this target\n",
    "    tr_smi = train_set[train_set['target_name'] == target]['std_smiles'].unique()\n",
    "    te_smi = test_set[test_set['target_name'] == target]['std_smiles'].unique()\n",
    "\n",
    "    # Match to descriptor matrix\n",
    "    tr_idx = [s for s in tr_smi if s in X_tr_full.index]\n",
    "    te_idx = [s for s in te_smi if s in X_te_full.index]\n",
    "\n",
    "    if len(tr_idx) < 50 or len(te_idx) < 20:\n",
    "        print(f'\\n{target}: SKIPPED (train={len(tr_idx)}, test={len(te_idx)} — too small)')\n",
    "        continue\n",
    "\n",
    "    # Scale and select features\n",
    "    X_tr_t = pd.DataFrame(scaler.transform(X_tr_full.loc[tr_idx]),\n",
    "                          columns=X_tr_full.columns, index=tr_idx)[features]\n",
    "    X_te_t = pd.DataFrame(scaler.transform(X_te_full.loc[te_idx]),\n",
    "                          columns=X_te_full.columns, index=te_idx)[features]\n",
    "\n",
    "    # Labels\n",
    "    y_tr_meta = train_set.drop_duplicates('std_smiles').set_index('std_smiles')\n",
    "    y_te_meta = test_set.drop_duplicates('std_smiles').set_index('std_smiles')\n",
    "    y_tr_t = (y_tr_meta.loc[tr_idx, 'activity_class'] == 'Active').astype(int)\n",
    "    y_te_t = (y_te_meta.loc[te_idx, 'activity_class'] == 'Active').astype(int)\n",
    "\n",
    "    # Check class balance\n",
    "    if y_tr_t.sum() < 10 or (len(y_tr_t) - y_tr_t.sum()) < 10:\n",
    "        print(f'\\n{target}: SKIPPED (insufficient class balance)')\n",
    "        continue\n",
    "\n",
    "    # Train RF\n",
    "    pipe = ImbPipeline([\n",
    "        ('smote', SMOTE(random_state=SEED)),\n",
    "        ('rf', RandomForestClassifier(n_estimators=500, random_state=SEED, n_jobs=-1))\n",
    "    ])\n",
    "    pipe.fit(X_tr_t, y_tr_t)\n",
    "    y_pred_t = pipe.predict(X_te_t)\n",
    "    y_prob_t = pipe.predict_proba(X_te_t)[:, 1]\n",
    "\n",
    "    ba = balanced_accuracy_score(y_te_t, y_pred_t)\n",
    "    f1 = f1_score(y_te_t, y_pred_t)\n",
    "    mcc = matthews_corrcoef(y_te_t, y_pred_t)\n",
    "    try:\n",
    "        auc = roc_auc_score(y_te_t, y_prob_t)\n",
    "    except ValueError:\n",
    "        auc = float('nan')\n",
    "\n",
    "    target_results.append({\n",
    "        'Target': target,\n",
    "        'Train_N': len(y_tr_t), 'Test_N': len(y_te_t),\n",
    "        'Train_Active_Pct': f'{y_tr_t.mean()*100:.1f}%',\n",
    "        'BA': ba, 'F1': f1, 'MCC': mcc, 'AUC': auc\n",
    "    })\n",
    "    print(f'\\n{target}: train={len(y_tr_t)}, test={len(y_te_t)}, BA={ba:.3f}, AUC={auc:.3f}')\n",
    "\n",
    "target_df = pd.DataFrame(target_results)\n",
    "print('\\n=== Target-Specific Model Results ===')\n",
    "print(target_df.round(3).to_string(index=False))\n",
    "target_df.to_csv(RESULTS / 'target_specific_results.csv', index=False)\n",
])

# ── Section: Activity Threshold Sensitivity ──
md([
    "## Part D — Activity Threshold Sensitivity (pIC50 = 5.0 vs 6.0)\n",
    "\n",
    "Does using a stricter threshold (pIC50 ≥ 6.0, i.e., IC50 ≤ 1 μM) improve model quality?"
])

code([
    "# ============================================================\n",
    "# CELL 6: Activity Threshold Sensitivity Analysis\n",
    "# ============================================================\n",
    "\n",
    "# Current threshold = 5.0 (IC50 ≤ 10 μM)\n",
    "# Alternative threshold = 6.0 (IC50 ≤ 1 μM, stricter)\n",
    "\n",
    "thresholds = [5.0, 5.5, 6.0]\n",
    "threshold_results = []\n",
    "\n",
    "for thresh in thresholds:\n",
    "    # Reclassify\n",
    "    y_tr_t = (y_train_df.loc[common_tr, 'pIC50'] >= thresh).astype(int)\n",
    "    y_te_t = (y_test_df.loc[common_te, 'pIC50'] >= thresh).astype(int)\n",
    "\n",
    "    n_active_tr = y_tr_t.sum()\n",
    "    n_active_te = y_te_t.sum()\n",
    "\n",
    "    if n_active_tr < 50 or (len(y_tr_t) - n_active_tr) < 50:\n",
    "        print(f'Threshold {thresh}: SKIPPED (class too imbalanced)')\n",
    "        continue\n",
    "\n",
    "    # Quick RF training\n",
    "    pipe = ImbPipeline([\n",
    "        ('smote', SMOTE(random_state=SEED)),\n",
    "        ('rf', RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1))\n",
    "    ])\n",
    "    pipe.fit(X_train, y_tr_t)\n",
    "    y_pred = pipe.predict(X_test)\n",
    "    y_prob = pipe.predict_proba(X_test)[:, 1]\n",
    "\n",
    "    ba = balanced_accuracy_score(y_te_t, y_pred)\n",
    "    f1 = f1_score(y_te_t, y_pred)\n",
    "    mcc = matthews_corrcoef(y_te_t, y_pred)\n",
    "    auc = roc_auc_score(y_te_t, y_prob)\n",
    "\n",
    "    threshold_results.append({\n",
    "        'Threshold': f'pIC50≥{thresh}',\n",
    "        'IC50_equiv': f'≤{10**(9-thresh)/1000:.0f} μM',\n",
    "        'Train_Active': n_active_tr,\n",
    "        'Train_Active_Pct': f'{n_active_tr/len(y_tr_t)*100:.1f}%',\n",
    "        'BA': ba, 'F1': f1, 'MCC': mcc, 'AUC': auc\n",
    "    })\n",
    "    print(f'Threshold pIC50≥{thresh}: Active={n_active_tr}/{len(y_tr_t)}, BA={ba:.3f}, AUC={auc:.3f}')\n",
    "\n",
    "thresh_df = pd.DataFrame(threshold_results)\n",
    "print('\\n=== Activity Threshold Sensitivity ===')\n",
    "print(thresh_df.round(3).to_string(index=False))\n",
    "thresh_df.to_csv(RESULTS / 'threshold_sensitivity.csv', index=False)\n",
])

# ── Section: Summary Figure ──
md(["## Summary Visualization"])

code([
    "# ============================================================\n",
    "# CELL 7: Summary Figures\n",
    "# ============================================================\n",
    "\n",
    "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
    "\n",
    "# Panel A: All models comparison\n",
    "ax = axes[0, 0]\n",
    "models_plot = results_df.copy()\n",
    "x = np.arange(len(models_plot))\n",
    "w = 0.2\n",
    "ax.bar(x - 1.5*w, models_plot['Balanced_Accuracy'], w, label='BA', color='#2196F3')\n",
    "ax.bar(x - 0.5*w, models_plot['F1'], w, label='F1', color='#4CAF50')\n",
    "ax.bar(x + 0.5*w, models_plot['MCC'], w, label='MCC', color='#FF9800')\n",
    "ax.bar(x + 1.5*w, models_plot['ROC_AUC'], w, label='AUC', color='#E91E63')\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(models_plot['Model'], rotation=30, ha='right', fontsize=9)\n",
    "ax.set_ylabel('Score')\n",
    "ax.set_title('Model Comparison — Test Set')\n",
    "ax.legend(fontsize=8)\n",
    "ax.set_ylim(0, 1.05)\n",
    "sns.despine(ax=ax)\n",
    "\n",
    "# Panel B: Confusion matrix for best model (stacking)\n",
    "ax = axes[0, 1]\n",
    "cm = confusion_matrix(y_test, stack_pred)\n",
    "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,\n",
    "            xticklabels=['Inactive', 'Active'], yticklabels=['Inactive', 'Active'])\n",
    "ax.set_xlabel('Predicted')\n",
    "ax.set_ylabel('Actual')\n",
    "ax.set_title('Stacking Ensemble — Confusion Matrix')\n",
    "\n",
    "# Panel C: Target-specific results\n",
    "ax = axes[1, 0]\n",
    "if len(target_df) > 0:\n",
    "    x = np.arange(len(target_df))\n",
    "    w = 0.25\n",
    "    ax.bar(x - w, target_df['BA'], w, label='BA', color='#2196F3')\n",
    "    ax.bar(x, target_df['AUC'], w, label='AUC', color='#E91E63')\n",
    "    ax.bar(x + w, target_df['MCC'], w, label='MCC', color='#FF9800')\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(target_df['Target'], rotation=30, ha='right')\n",
    "    ax.set_ylabel('Score')\n",
    "    ax.set_title('Target-Specific RF Models')\n",
    "    ax.legend(fontsize=8)\n",
    "    ax.set_ylim(0, 1.05)\n",
    "else:\n",
    "    ax.text(0.5, 0.5, 'No target-specific results', ha='center', va='center',\n",
    "            transform=ax.transAxes)\n",
    "sns.despine(ax=ax)\n",
    "\n",
    "# Panel D: Threshold sensitivity\n",
    "ax = axes[1, 1]\n",
    "if len(thresh_df) > 0:\n",
    "    x = np.arange(len(thresh_df))\n",
    "    w = 0.25\n",
    "    ax.bar(x - w, thresh_df['BA'], w, label='BA', color='#2196F3')\n",
    "    ax.bar(x, thresh_df['AUC'], w, label='AUC', color='#E91E63')\n",
    "    ax.bar(x + w, thresh_df['MCC'], w, label='MCC', color='#FF9800')\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(thresh_df['Threshold'])\n",
    "    ax.set_ylabel('Score')\n",
    "    ax.set_title('Activity Threshold Sensitivity')\n",
    "    ax.legend(fontsize=8)\n",
    "    ax.set_ylim(0, 1.05)\n",
    "sns.despine(ax=ax)\n",
    "\n",
    "plt.suptitle('Notebook 07 — Consensus & Advanced Analysis Summary', fontsize=14)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES / 'nb07_advanced_analysis.png', dpi=200, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Figure saved: figures/nb07_advanced_analysis.png')\n",
])

# ── Cell 8: Save Final Results ──
code([
    "# ============================================================\n",
    "# CELL 8: Save All Results + QC-7\n",
    "# ============================================================\n",
    "\n",
    "results_df.to_csv(RESULTS / 'test_set_all_models.csv', index=False)\n",
    "print('Saved: results/model_metrics/test_set_all_models.csv')\n",
    "\n",
    "print()\n",
    "print('=' * 60)\n",
    "print('QUALITY CONTROL CHECKPOINT QC-7')\n",
    "print('=' * 60)\n",
    "\n",
    "best = results_df.loc[results_df['Balanced_Accuracy'].idxmax()]\n",
    "print(f'Best model: {best[\"Model\"]} (BA={best[\"Balanced_Accuracy\"]:.4f})')\n",
    "\n",
    "checks = {}\n",
    "checks[f'Best BA > 0.70 (actual: {best[\"Balanced_Accuracy\"]:.3f})'] = best['Balanced_Accuracy'] > 0.70\n",
    "checks[f'Best AUC > 0.80 (actual: {best[\"ROC_AUC\"]:.3f})'] = best['ROC_AUC'] > 0.80\n",
    "checks[f'Best MCC > 0.30 (actual: {best[\"MCC\"]:.3f})'] = best['MCC'] > 0.30\n",
    "checks[f'Consensus/Stacking improves over single models'] = (\n",
    "    results_df[results_df['Model'].isin(['Consensus (≥3/4)', 'Stacking (LR meta)'])]\n",
    "    ['Balanced_Accuracy'].max() >= results_df[~results_df['Model'].isin(['Consensus (≥3/4)', 'Stacking (LR meta)'])]\n",
    "    ['Balanced_Accuracy'].max() - 0.01\n",
    ")\n",
    "\n",
    "all_pass = True\n",
    "for check, passed in checks.items():\n",
    "    sym = 'PASS' if passed else 'FAIL'\n",
    "    print(f'  [{sym}] {check}')\n",
    "    if not passed: all_pass = False\n",
    "\n",
    "print('=' * 60)\n",
    "if all_pass:\n",
    "    print('QC-7 PASSED — Consensus analysis complete')\n",
    "else:\n",
    "    print('QC-7: Some checks need review')\n",
    "print('=' * 60)\n",
])

# ── Build notebook ──
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "PhD QSAR Leishmania",
            "language": "python",
            "name": "qsar-leish"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Created: {NB_PATH}")
print(f"  Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
